// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtybJw6Bh81HhWCWWNC3pPXBnQ05DXixI',
    appId: '1:503853682022:web:735ae14677fa5fc9914ca7',
    messagingSenderId: '503853682022',
    projectId: 'shawarmaversion2',
    authDomain: 'shawarmaversion2.firebaseapp.com',
    databaseURL: 'https://shawarmaversion2-default-rtdb.firebaseio.com',
    storageBucket: 'shawarmaversion2.appspot.com',
    measurementId: 'G-6YREHX82L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp7rhw40rfzQw8s5j1TDuOxUOXI5tJTuI',
    appId: '1:503853682022:android:0e2898acb315424a914ca7',
    messagingSenderId: '503853682022',
    projectId: 'shawarmaversion2',
    databaseURL: 'https://shawarmaversion2-default-rtdb.firebaseio.com',
    storageBucket: 'shawarmaversion2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3GU0RHUGhvvGUAMVseDn8RcXLwuCyG4I',
    appId: '1:503853682022:ios:c2c1bf1b7d09565c914ca7',
    messagingSenderId: '503853682022',
    projectId: 'shawarmaversion2',
    databaseURL: 'https://shawarmaversion2-default-rtdb.firebaseio.com',
    storageBucket: 'shawarmaversion2.appspot.com',
    iosBundleId: 'com.example.shawarmaversion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3GU0RHUGhvvGUAMVseDn8RcXLwuCyG4I',
    appId: '1:503853682022:ios:7e63cc0a3bf62bfd914ca7',
    messagingSenderId: '503853682022',
    projectId: 'shawarmaversion2',
    databaseURL: 'https://shawarmaversion2-default-rtdb.firebaseio.com',
    storageBucket: 'shawarmaversion2.appspot.com',
    iosBundleId: 'com.example.shawarmaversion2.RunnerTests',
  );
}
